### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Iridahonda** [alistair23/AutoMower-BLE#10]
I am using a 405X. This integration is working, but is it possible to add:

1. GPS coordinates.  The official Husqvarna API is really really slow so it would be much better to get the position via bluetooth.

2. Next start time. 

Cheers

/T

**Comment by erikmol** [comment]
I've added support for "next start time" in my [repo,](https://github.com/erikmol/AutoMower-BLE/commit/17a6cdf536d130102a1a486e922fc81a6f3e6a23) but due to the high amount of code duplication I think it make sense to re-structure some code to add features more easily. I made a quick (but incomplete) example [here](https://github.com/erikmol/AutoMower-BLE/commit/c5e1a257978050d7f4ee19a7a1b89415037ac574#diff-46c7cef6e8dc655f6e02e5d69db83dae11e53bd8e3e1e6c709fbad793cde1d0aR91).

Thus I would like to pivot the discussion on how to make the code base more flexible in terms of adding new commands. Perhaps having the command in a .json file such as this makes sense? Seeing [other development](https://github.com/tgillbe/flymo2mqtt/blob/master/src/mower/packets.py) on this topic, the list of commands can be huge.
```
{
    "nextStartTime": {
        "major": 4658,
        "minor": 1,
        "responseType": "tUnixTime"
    },
    "getMessage": {
        "major": 4730,
        "minor": 1,
        "requestType": {
            "messageId": "uint32"
        },
        "responseType": {
            "messageTime": "tUnixTime",
            "code": "uint32",
            "severity": "uint8"
        }
    }
}
```

**Comment by Iridahonda** [comment]
Thanks.  Think it makes very good sense to have the structure readily configurable for new stuff.  There are as you say a lot of commands and sensors available.  The Hass Husqvarana API from Thomas55555 includes most if not all:

https://github.com/Thomas55555/husqvarna_automower/blob/main/custom_components/husqvarna_automower/

**Comment by erikmol** [comment]
I started an to rewrite the request/response code according to my previous proposal in [this branch](https://github.com/erikmol/AutoMower-BLE/tree/protocol-structure). Any feedback or comments @alistair23 ?

**Comment by alistair23** [comment]
> I've added support for "next start time" in my [repo](https://github.com/erikmol/AutoMower-BLE/commit/17a6cdf536d130102a1a486e922fc81a6f3e6a23)

Awesome! Do you want to submit a PR. That would be a great feature to support.

> Thus I would like to pivot the discussion on how to make the code base more flexible in terms of adding new commands. Perhaps having the command in a .json file such as this makes sense? Seeing [other development](https://github.com/tgillbe/flymo2mqtt/blob/master/src/mower/packets.py) on this topic, the list of commands can be huge.

Yep! I'm all ears for a refactor. This project just started as a way to test commands, so it isn't that scalable for the large range of commands.

Parsing a json file sounds reasonable to me. I'm not very experience with Python, so I'm open to any ideas.

> I started an to rewrite the request/response code according to my previous proposal in [this branch](https://github.com/erikmol/AutoMower-BLE/tree/protocol-structure). Any feedback or comments @alistair23 ?

This looks like a good approach to me

**Comment by Iridahonda** [comment]
Thanks for this.  I updated my manifest to point to git and got the library updated but I dont see next_start_time in Hass.  Do I need to update the custom component coordinator so it requests it?

**Comment by erikmol** [comment]
> Thanks for this. I updated my manifest to point to the git and got the library updated but I dont see next_start_time in Hass. 

There is nothing Home Assistant specific to this repo. This repo is just a general purpose library which can be used standalone, by Home Assistant, or other systems. This means that new features needs to first land in this repo and later integrated into Home Assistant. As the Home Assistant [pull request](https://github.com/home-assistant/core/pull/108326) is still not merged, it's hard to suggest new features for Home Assistant as there is no home for this code.

> Do I need to update the custom component coordinator so it requests it?

It needs some updates, yes. Unfortunately I'm not very familiar with the HA components code structure so I can't help you.
