### ISSUE TITLE
Any update about homeassistant-core native integration?

### ISSUE THREAD

**Issue by al31c0** [alistair23/AutoMower-BLE#16]
Hi @alistair23,

I sow few weeks ago that you are trying to push this integration natively to homeassinstat-core.

Do you have any update to share? Can we help somehow to push this process?

And also can you share the GitHub webpage link to see this process?

I know that's not an issue but I'm not able to find the link anymore (via google search).

**Comment by alistair23** [comment]
The PR is here: https://github.com/home-assistant/core/pull/108326

I recently received a little bit of feedback so I will need to address that. As for helping I think commenting on the PR saying that you are using it and would like to see it merged will help.
