### ISSUE TITLE
Add minimo 500

### ISSUE THREAD

**Issue by djungelola** [alistair23/AutoMower-BLE#26]
Hi
Please add Gardena Sileno Minimo 500, key=29,3.
response: b'02fd1300a6c0fa6a017501af5a1209000002001d039303'

1d 03-> [29,3]

Br Ola

**Comment by alistair23** [comment]
Send a PR please :)

https://github.com/alistair23/AutoMower-BLE/blob/main/automower_ble/models.py#L42

**Comment by djungelola** [comment]
My first PR ever :-) Lets hope i did it correct.

/Ola
