### ISSUE TITLE
Mode of operation minor correct ? 

### ISSUE THREAD

**Issue by enicky** [alistair23/AutoMower-BLE#29]
I saw in the newly merged code, in the protocol.json file the following : 
```
 "modeOfOperation": {
        "major": 4586,
        "minor": 1,
        "requestType": {
            "mode": "uint8"
        },
        "responseType": "no_response",
        "description": "Set mode of operation."
    },
```

but according to the code from the Gardena app, minor 1 appears to be the GET request ? Minor 0 is the set command  ?

**Comment by erikmol** [comment]
The recent changes just mirrors the [previous code](https://github.com/alistair23/AutoMower-BLE/blob/abec9364fe1378e3ad137c19c885915a75377585/automower_ble/request.py#L19) where there is [data sent](https://github.com/alistair23/AutoMower-BLE/blob/abec9364fe1378e3ad137c19c885915a75377585/automower_ble/request.py#L242) (as the author of #15 , I just want to empathize that it's not related to that PR).

Based on the logs provided in [another issue](https://github.com/alistair23/AutoMower-BLE/issues/3#issuecomment-2065353285) it seems like you are correct:
-  `4586, 0` is sent with data and without any response
- `4586, 1` is sent without data but with a uint8 response.

As you have #23 in progress you can perhaps change and add these as `getModeOfOperation`and `setModeOfOperation` and update [mower.py](https://github.com/alistair23/AutoMower-BLE/blob/11f91d819f5e3d5cf903748ecfe3dd071c8c628b/automower_ble/mower.py#L101C35-L101C50) accordingly

**Comment by alistair23** [comment]
Yeah, it seems like they are around the wrong way. If you can send a PR that would be great :)

**Comment by enicky** [comment]
PR has been created : #32
