### ISSUE TITLE
Getting Startet and Install Instruction

### ISSUE THREAD

**Issue by wlan4you** [alistair23/AutoMower-BLE#4]
Hello,

have you a getting startet and a install instruction for a beginner with a Raspberry Pi ?
Home Assistant, MQTT, Node-RED and so on is Running on the newest Version

I installed now the ESP32 Bluetooth Proxy and my Home Assistant find that ESP32 also.

I will help you to bring up forward you Project.
We have a, for your Database
:
AutoMower 420
Software:
Main: 7.04.00
HMI: 6.07.00
SUB: 6.00.00
COM: 0.00.00

**Comment by alistair23** [comment]
https://github.com/alistair23/AutoMower-BLE/issues/5#issuecomment-2041392659
