### ISSUE TITLE
Husqvarna 310 MARK II | No reconnect after being disconnected for >20min

### ISSUE THREAD

**Issue by jenssvedlund** [alistair23/AutoMower-BLE#40]
Great integration, many thanks for you work!
Been trying it out for a while and seems like after it's been disconnected for a while it never re-establishes the connection. 
This is the log from the Bluetooth Proxy when it fails:
![image](https://github.com/alistair23/AutoMower-BLE/assets/128328187/6278d6ae-2681-4844-85b5-95993eb54413)

**Comment by AlessandroTischer** [comment]
I have exactly the same problem

**Comment by alistair23** [comment]
I have had reliability issues as well. It **seems** to be an issue on the ESPHome side. So it's probably worth raising an issue there with the log (although a text log not a picture). That failure reason might shed some light on what is going on

**Comment by alistair23** [comment]
I have not had any issues recently with the latest HA and ESPHome so I'm going to close this
