### ISSUE TITLE
Install guide for noobs

### ISSUE THREAD

**Issue by al31c0** [alistair23/AutoMower-BLE#43]
Hi guys,

I want to test this integration with my Automower 305 with ESPHome Bluetooth Proxy.

I sow the installation guide of this comment but I need more detail to start. I'm not an expert so I ask you to provide a simple step-by-step guide to install.

Can you help me?? Thank you so much. 

https://github.com/home-assistant/home-assistant.io/pull/30921#issuecomment-2017744301

**Comment by al31c0** [comment]
From what I understood until now I should:

- open terminal in HA
- run: `git clone <[url_of_remote_repository](https://github.com/alistair23/AutoMower-BLE>`
- run: `pip3 install automower-ble`
- restart HA

and then?

**Comment by alistair23** [comment]
The steps are available at: https://github.com/home-assistant/home-assistant.io/pull/30921#issuecomment-2017744301

If that is too complex your best bet is to wait for HA to merge my PR. I don't want to go down the path of supporting manual installs. Then I will end up supporting installation issues and compatibility between different versions

**Comment by al31c0** [comment]
I just need some steps to follow and learn by doing :) If you have 5 minutes to help me I will be very grateful. I have been waiting for weeks for the official integration but I see that it still takes time. I would simply like to try manual installation. If it doesn't go the first time, I won't bother with further comments.
