### ISSUE TITLE
Request for info

### ISSUE THREAD

**Issue by berlund** [alistair23/AutoMower-BLE#45]
Hi!

A while ago, someone posted a manual how to get around the pin entry on a Gardena mower as part of a PR. Unfortunately I cannot find it any longer. Could anyone hint me to the correct post or is it already documented somewhere?

**Comment by nsiicm0** [comment]
i have used this instructions in the past which helped me: https://github.com/alistair23/AutoMower-BLE/issues/3#issuecomment-2055774336
