### ISSUE TITLE
How to get new fork working in Home Assistant

### ISSUE THREAD

**Issue by idominiki** [alistair23/AutoMower-BLE#49]
Hey @alistair23 !

Sorry for opening this issue first, but you mentioned that Gardena Support can be working now, as multiple models are now listed in models.py

But how can I fork this build to custom_components to test this out?

Thanks for a tip!
Dominik

**Comment by alistair23** [comment]
https://github.com/home-assistant/home-assistant.io/pull/30921#issuecomment-2017744301
