### ISSUE TITLE
Battery Entity no longer provided?

### ISSUE THREAD

**Issue by AlessandroTischer** [alistair23/AutoMower-BLE#61]
Hello, I updated the component in home assistant and I noticed it doesn't provide the battery status entity anymore. Is this correct? If so, why was it removed? In my case (Husqvarna AM 315) it worked just fine. 

Also, I see there were a lot of commits reguarding adding commands and error descriptions on this repository, but I still see only start, stop, dock commands on the mower device entity. Again, am I missing something?

Thank you for the support and the fantastic work you are doing!!

**Comment by alistair23** [comment]
As part of upstreaming to HA I had to remove the battery support. Hopefully once it is accepted upstream we can re-add battery and other advanced features
