### ISSUE TITLE
home-assistant component refactor

### ISSUE THREAD

**Issue by andyb2000** [alistair23/AutoMower-BLE#66]
Hi @alistair23 
Sorry if this is the wrong place, but I'd noted the constant problems trying to fit into the HA component framework so I'm having a go at refactor of the code to also incorporate all the sensors we have available.
Not sure if it's something worth collaborating on to get it past the home-assistant code authors/approvers or if you're far enough to complete what you already submitted to them and I'll then do PR's against that to add extra functions, sensors, etc.

https://github.com/andyb2000/homeassistant-core-husq/tree/andyb2000/husqvarna_automower_ble_fullstats/homeassistant/components/husqvarna_automower_ble

Regards,
Andy

**Comment by alistair23** [comment]
Awesome! Thanks for that

I think at the moment I want to focus on getting the inital bare bones into HA. I have some comments I need to address when I find the time.

From some of the review comments it seems like it's going to be a lot easier to get a simple setup upstream first then build on that.

So it would be best for you to submit PRs against the HA component when it is eventually merged

Thanks for this work though, it's great to see more support. It is a good motivation for me to dedicate some time to address the current review comments

**Comment by andyb2000** [comment]
Makes sense, yes I've noticed they can be quite picky over formatting and structure!
I'll keep my code on standby and hopefully once you've got the base in I'll submit against.
Thanks for all your work so far Alistair it's much appreciated.


On June 29, 2024 3:15:55 AM GMT+01:00, Alistair Francis ***@***.***> wrote:
>Awesome! Thanks for that
>
>I think at the moment I want to focus on getting the inital bare bones into HA. I have some comments I need to address when I find the time.
>
>From some of the review comments it seems like it's going to be a lot easier to get a simple setup upstream first then build on that.
>
>So it would be best for you to submit PRs against the HA component when it is eventually merged
>
>Thanks for this work though, it's great to see more support. It is a good motivation for me to dedicate some time to address the current review comments
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/alistair23/AutoMower-BLE/issues/66#issuecomment-2197856980
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by erikmol** [comment]
Great work Andy. As @alistair23 suggests, it would be best to keep the initial commit to a bare minimum according to the [development guidelines](https://developers.home-assistant.io/docs/creating_component_code_review#5-make-your-pull-request-as-small-as-possible). 

It is an unfortunate mix with all Bluetooth topics; auto discovery, config flows, unit tests, etc. on top of HA strict code quality and slow review. Keep pushing @alistair23 ! Once the initial PR gets accepted I guess people will discover this great work and there will be some inflow of contributors which can contribute easily to the HA component as the upstream library is reaching a mature state.

**Comment by alistair23** [comment]
Initial HA support is now merged! It will be included in the next release.

I have opened a PR to update the dependency: https://github.com/home-assistant/core/pull/129473

It would be great to get more people testing https://github.com/home-assistant/core/pull/129473 and after that start working on supporting more sensors, features and commands
