### ISSUE TITLE
HA native integration update - Step-by-step installation

### ISSUE THREAD

**Issue by al31c0** [alistair23/AutoMower-BLE#68]
Good morning everyone,

I am impatiently waiting the native integration in Home Assistant of this project but I see that it has stalled. Can you give us an update on this? 

Alternatively, is it possible to have a step-by-step procedure for the non-native installation?

Thank you for your time and incredible work.

**Comment by andyb2000** [comment]
Hi, unfortunately it's quite complex to get it added in as a native integration and alistair23 is working hard to get round the obstacles in doing so.
In the meantime (and I don't want to step on any toes here) I have created a HACS repo (mainly for my own use) to get this working in my home-assistant. It has a bug in that additional sensors (battery, time mowing, next start, etc) don't currently appear but it has the install steps you need to setup the ESP32 BLE proxy and get it into your HA - https://github.com/andyb2000/HACS-husqvarna_automower_ble/

**Comment by LasseBang** [comment]
> Hi, unfortunately it's quite complex to get it added in as a native integration and alistair23 is working hard to get round the obstacles in doing so. In the meantime (and I don't want to step on any toes here) I have created a HACS repo (mainly for my own use) to get this working in my home-assistant. It has a bug in that additional sensors (battery, time mowing, next start, etc) don't currently appear but it has the install steps you need to setup the ESP32 BLE proxy and get it into your HA - https://github.com/andyb2000/HACS-husqvarna_automower_ble/
> 
> I fully expect my HACS repo to be binned once the native integration goes in and we can then do PR's against that to update it.

Awesome job!

**Comment by alistair23** [comment]
Closing this issue as HA now supports Automowers in the next release :)

**Comment by alistair23** [comment]
In the meantime, if people are able to test https://github.com/home-assistant/core/pull/129473 that would be really helpful
