### ISSUE TITLE
Request for pypi library to be updated

### ISSUE THREAD

**Issue by andyb2000** [alistair23/AutoMower-BLE#71]
Pypi/python libraries are still using an older version of the library (with request.py etc).
Can this be pushed as an update to have the supported models, etc, updated?

**Comment by alistair23** [comment]
I'm a little stuck waiting for https://github.com/home-assistant/core/pull/108326 to be merged. After that I will make a new release

**Comment by andyb2000** [comment]
Ah understood, didn't realise the pypi/python libraries were stuck as a dependency on the ha integration

**Comment by andyb2000** [comment]
Closing as I can work around it :)

**Comment by alistair23** [comment]
Finally updated!

https://pypi.org/project/automower-ble/0.2.0/
