### ISSUE TITLE
Inquiry About Future Arduino/C++ Support

### ISSUE THREAD

**Issue by FrankDoersam** [alistair23/AutoMower-BLE#76]
Hello,

First, I want to express my appreciation for your excellent work on the library—it’s truly impressive!

I was wondering if there are any plans to provide support for Arduino or C++ in the future.

Thank you for your time and consideration.

Best regards,
Frank

**Comment by alistair23** [comment]
No plans for Arduino or C support. This library is for Home Assistant support, that's all I'm interested in.

It shouldn't be too hard to use the protocol code here to write a C library though (I would use Rust though :) )
