### ISSUE TITLE
Multiple bt-proxies

### ISSUE THREAD

**Issue by djungelola** [alistair23/AutoMower-BLE#77]
Hi
To cover my yard i need to have two proxies for full coverage for my Garden Minimo 500.
Seems like the mower only can pair to one proxy at the time. When the proxy that hasnt been paired take over the coverage i get the "insufficient encryption" error. When paired to that proxy the other one gets the same issue.

Anyone who has a workaround for this?

Br Ola

**Comment by alistair23** [comment]
You need to manually pair against each proxy. So basically set only one proxy up, put the mower into pairing mode then setup the integration. Then turn that proxy off, setup the second one and repeat the process.

The mower need to be paired with each BLE device

**Comment by djungelola** [comment]
Thanks! Will try that :-)
