### ISSUE TITLE
Integration with Node-RED

### ISSUE THREAD

**Issue by krambriw** [alistair23/AutoMower-BLE#79]
Hello, nice project!
Don't have a mover but my friend has one. Just wondering some things before starting testing:
- the python scripts, do you recommend to run everything on a Raspberry Pi or is it ok with a mac book or win computer?
- the Raspberry BT device supports BLE, can that integrated device be used or is it necessary to always use a separate ESP32 proxy?

I plan to integrate with Node-RED using MQTT (instead of HA) so I will add MQTT support either to some python script or directly in the ESP32 proxy device

With kind regards, Walter

**Comment by alistair23** [comment]
> * the python scripts, do you recommend to run everything on a Raspberry Pi or is it ok with a mac book or win computer?

I don't have a Raspberry Pi, so I can't comment if that's a good idea or not. The scripts should work fine on any Linux environment though

> * the Raspberry BT device supports BLE, can that integrated device be used or is it necessary to always use a separate ESP32 proxy?

The ESP32 Proxy is just for Home Assistant as it's the recommended way to communicate with BLE devices.

> I plan to integrate with Node-RED using MQTT (instead of HA) so I will add MQTT support either to some python script or directly in the ESP32 proxy device

Any device that supports BLE and can then forward the data over MQTT should work for that then
