### ISSUE TITLE
Getting pin of the device

### ISSUE THREAD

**Issue by jimmyd-be** [alistair23/AutoMower-BLE#82]
I have a Gardana Sileno Minomi 500. I want to use this library for a Hass integration to control the device from evreywerhere.
But it looks like I need to have a pin code to do so. How can I get my pin code because the device has a pin code related to the few buttons is has?

**Comment by alistair23** [comment]
https://github.com/alistair23/AutoMower-BLE/issues/63#issuecomment-2162464589

**Comment by alistair23** [comment]
https://github.com/alistair23/AutoMower-BLE/issues/53#issuecomment-2254270144

**Comment by alistair23** [comment]
https://github.com/alistair23/AutoMower-BLE/issues/63#issuecomment-2163097449

**Comment by alistair23** [comment]
The three comments above all seem to indicate the same pattern, so that should work for you. If it does can you please open a PR against https://github.com/home-assistant/home-assistant.io/ and this repo to update the documentation to help others
